const images = {
  apple: require('./imgs/apple-logo.png'),
  google: require('./imgs/google-logo.png'),
  kakao: require('./imgs/kakao-logo.png'),
  logo: require('./imgs/logo.png'),
  back: require('./icons/back-icon.png'),
  search: require('./icons/search-icon.png'),
  bigSearch: require('./icons/big-search.png'),
  alarm: require('./icons/alarm-icon.png'),
  hamber: require('./icons/hamber-icon.png'),
  user: require('./icons/user-icon.png'),
  arrowLeft: require('./icons/arrow-right-icon.png'),
  arrowDown: require('./icons/arrow-down-icon.png'),
  calendar: require('./icons/calendar-icon.png'),
  account: require('./icons/account-icon.png'),
  uploadAccount: require('./icons/user-icon.png'),
  plus: require('./icons/plus-icon.png'),
  bigPlus: require('./icons/big-plus-icon.png'),
  setting: require('./icons/setting-icon.png'),
  plusWhite: require('./icons/plus-white-icon.png'),
  close: require('./icons/close-icon.png'),
  loading: require('./icons/loading.gif'),
  list: require('./icons/calendar-icon.png'),
  intro1: require('./intros/intro1.png'),
  intro2: require('./intros/intro2.png'),
  intro3: require('./intros/intro3.png'),
  intro4: require('./intros/intro4.png'),
  consumed: require('./icons/consumed-icon.png'),
  share: require('./icons/share-icon.png'),
  public: require('./icons/public-icon.png'),
  kakaoShare: require('./icons/kakao-button-icon.png'),
  pinkShare: require('./icons/pink-share-icon.png'),
};

export default images;
